Added variables.tf Added clean "-c" command to setup. Updated example.env

diff --git a/infra/azure/setup b/infra/azure/setup
--- a/infra/azure/setup
+++ b/infra/azure/setup
@@ -1,99 +1,143 @@
 #!/bin/bash
 # Setup a Hail batch deployment on Azure.
+# Usage ./setup [-c]
+#   -c: Clean up local and remote Terraform state.
 #
 # Script should follow style https://google.github.io/styleguide/shellguide.html
 #
 # Environment variables that need to be set or provided with `-f .env`. See also `example.env`.
 #   - AAD_TENANT
+#   - AZURE_SUBSCRIPTION
 #   - AZHAIL_PREFIX
 #   - RESOURCE_GROUP_NAME
 #   - LOCATION
 #   - STORAGE_ACCOUNT
-#   - AZURE_SUBSCRIPTION
 #   - TERAFORM_CONTAINER
+#   - dns_prefix
+#   - ssh_public_key
+#   - cluster_name
+
+export AAD_TENANT="to do"
+export AZURE_SUBSCRIPTION="to do"
+export AZHAIL_PREFIX="azhaildev0"
+export RESOURCE_GROUP_NAME="${AZHAIL_PREFIX}-rg"
+export LOCATION="westus2"
+export STORAGE_ACCOUNT="${AZHAIL_PREFIX}sa"
+export TERAFORM_CONTAINER="${AZHAIL_PREFIX}-tfstate"
+export ssh_public_key="file path to public key"
+
+#############
+# Constants #
+#############
+
+# Command line options.
+readonly GETOPTS_STR="c"
 
 main() {
-# Report terraform version
-    terraform -v
+  # Process options.
+  while getopts "${GETOPTS_STR}" option; do
+    case "${option}" in
+      c) should_clean="true";;
+    esac
+  done
 
-    # Report Azure CLI verison
-    az --version
+  # Report terraform version
+  terraform -v
 
-    # Load variables we need from a .env file if specified. Ignoring comments.
-    if [ -f .env ]; then
-        echo "Found .env file. Sourcing it."
-      source ".env"
-    else
-      echo "No .env found, assuming environment variables are set already."
+  # Report Azure CLI verison
+  az --version
+
+  # Load variables we need from a .env file if specified. Ignoring comments.
+  if [ -f .env ]; then
+      echo "Found .env file. Sourcing it."
+    source ".env"
+  else
+    echo "No .env found, assuming environment variables are set already."
+  fi
+
+  # Login to Azure using the specified tenant if not already logged in.
+  2>/dev/null az account get-access-token --tenant "${AAD_TENANT}" --output none
+  if [[ $? -ne 0 ]] ; then
+    echo "Login required to authenticate with Azure."
+    echo "Attempting to login to Tenant: ${AAD_TENANT}"
+    az login --output none --tenant "${AAD_TENANT}"
+    if [[ $? -ne 0 ]]; then
+      err "Failed to authenticate with Azure"
     fi
+  fi
 
-    # Login to Azure using the specified tenant if not already logged in.
-    2>/dev/null az account get-access-token --tenant "${AAD_TENANT}" --output none
-    if [[ $? -ne 0 ]] ; then
-      echo "Login required to authenticate with Azure."
-      echo "Attempting to login to Tenant: ${AAD_TENANT}"
-      az login --output none --tenant "${AAD_TENANT}"
-      if [[ $? -ne 0 ]]; then
-        err "Failed to authenticate with Azure"
-      fi
-    fi
+  # Set the subscription so future commands don't need to specifiy it.
+  az account set --subscription "${AZURE_SUBSCRIPTION}"
 
-    # Set the subscription so future commands don't need to specifiy it.
-    az account set --subscription "${AZURE_SUBSCRIPTION}"
-
-    # Create resource group if it doesn't exist.
-    # When a resource group doesn't exist, the `az group exists` command returns anauthorization error.
-    echo "Checking if resource group ${RESOURCE_GROUP_NAME} exists."
-    rg_exists=$(2>/dev/null az group exists -n "${RESOURCE_GROUP_NAME}" --subscription "${AZURE_SUBSCRIPTION}")
-    if [[ ${rg_exists} == "true" ]]; then
-       echo "Resource group ${RESOURCE_GROUP_NAME} already exists."
-    else
-      echo "Resource group ${RESOURCE_GROUP_NAME} does not exist."
-      echo "Creating resource group ${RESOURCE_GROUP_NAME}"
-      1>/dev/null az group create --name "${RESOURCE_GROUP_NAME}" --location "${LOCATION}"
-    fi
-
-    # Create storage account if it doesn't exist.
-    # Uses jq to parse the json output and grab the "nameAvailable" field.
-    echo "Checking if storage account ${STORAGE_ACCOUNT} exists."
-    sa_exists=$(2>/dev/null az storage account check-name -n "${STORAGE_ACCOUNT}" --subscription "${AZURE_SUBSCRIPTION}" | jq .nameAvailable)
-    if [[ ${sa_exists} == "false" ]]; then
-        echo "Storage account ${STORAGE_ACCOUNT} exists."
-    else
-        echo "Storage account ${STORAGE_ACCOUNT} does not exist. Creating it."
-        1>/dev/null az storage account create --name "${STORAGE_ACCOUNT}" --resource-group "${RESOURCE_GROUP_NAME}" --location "${LOCATION}" --subscription "${AZURE_SUBSCRIPTION}"  --auth-mode login
-    fi
-
-    # Create container to store teraform information if it doesn't exist.
-    # Uses jq to parse the json output and grab the "exists" field.
-    container_exists=$(2>/dev/null az storage container exists -n "${TERAFORM_CONTAINER}" --account-name "${STORAGE_ACCOUNT}" --subscription "${AZURE_SUBSCRIPTION}" --auth-mode login | jq .exists)
-    if [[ ${container_exists} == "false" ]]; then
-        echo "Creating container ${TERAFORM_CONTAINER}"
-        1>/dev/null az storage container create -n "${TERAFORM_CONTAINER}" --account-name "${STORAGE_ACCOUNT}" --subscription "${AZURE_SUBSCRIPTION}" --auth-mode login
-    else
-        echo "Container ${TERAFORM_CONTAINER} exists."
-    fi
-
-    # Get an access key to the storage account.
-    # Use jq to grabe the "value" field of the first key. "-r" option gives raw output without quotes.
-    local sa_access_key=$(az storage account keys list --resource-group "${RESOURCE_GROUP_NAME}" --account-name "${STORAGE_ACCOUNT}" --subscription "${AZURE_SUBSCRIPTION}" | jq -r .[0].value)
-
-    #### Create AKS cluster with Terraform ####
-
-    # Initialize Terraform with a blob container to store state.
-    terraform init -backend-config="storage_account_name=${STORAGE_ACCOUNT}" -backend-config="container_name=${TERAFORM_CONTAINER}" -backend-config="access_key=${sa_access_key}" -backend-config="key=codelab.microsoft.tfstate"
+  # Check if we are running the clean command.
+  if [[ -n ${should_clean} ]]; then
+    echo "Cleaning Terraform state."
     
-    # Import the existing resource group into the configuration because we don't have perms to have Terraform be the creator of the resource group.
-    terraform import  -var resource_group_name="${RESOURCE_GROUP_NAME}" -var location="${LOCATION}" -var log_analytics_workspace_location="${LOCATION}" "azurerm_resource_group.k8s" "/subscriptions/${AZURE_SUBSCRIPTION}/resourceGroups/${RESOURCE_GROUP_NAME}"
+    # Remove local Terraform state.
+    rm -rf ".terraform"
+    rm .terraform.lock.hcl
+    rm out.plan
 
-    # Have Terraform create a plan and save it to file.
-    terraform plan  -out out.plan -var resource_group_name="${RESOURCE_GROUP_NAME}" -var location="${LOCATION}" -var log_analytics_workspace_location="${LOCATION}"
+    # Remove Terraform container.
+    az storage container delete -n "${TERAFORM_CONTAINER}" --account-name "${STORAGE_ACCOUNT}" --subscription "${AZURE_SUBSCRIPTION}" --auth-mode login
 
-    # Apply the Terraform configuation.
-    # This will fail until we fix
-    # - The subscription is not registered to use namespace 'Microsoft.OperationsManagement'. See https://aka.ms/rps-not-found for how to register subscriptions.","target":"Microsoft.OperationsManagement"}
-    # - either an `identity` or `service_principal` block must be specified for cluster authentication
-    #terraform apply out.plan
+    exit 0
+  fi
+
+
+  # Create resource group if it doesn't exist.
+  # When a resource group doesn't exist, the `az group exists` command returns anauthorization error.
+  echo "Checking if resource group ${RESOURCE_GROUP_NAME} exists."
+  rg_exists=$(2>/dev/null az group exists -n "${RESOURCE_GROUP_NAME}" --subscription "${AZURE_SUBSCRIPTION}")
+  if [[ ${rg_exists} == "true" ]]; then
+      echo "Resource group ${RESOURCE_GROUP_NAME} already exists."
+  else
+    echo "Resource group ${RESOURCE_GROUP_NAME} does not exist."
+    echo "Creating resource group ${RESOURCE_GROUP_NAME}"
+    1>/dev/null az group create --name "${RESOURCE_GROUP_NAME}" --location "${LOCATION}"
+  fi
+
+  # Create storage account if it doesn't exist.
+  # Uses jq to parse the json output and grab the "nameAvailable" field.
+  echo "Checking if storage account ${STORAGE_ACCOUNT} exists."
+  sa_exists=$(2>/dev/null az storage account check-name -n "${STORAGE_ACCOUNT}" --subscription "${AZURE_SUBSCRIPTION}" | jq .nameAvailable)
+  if [[ ${sa_exists} == "false" ]]; then
+      echo "Storage account ${STORAGE_ACCOUNT} exists."
+  else
+      echo "Storage account ${STORAGE_ACCOUNT} does not exist. Creating it."
+      1>/dev/null az storage account create --name "${STORAGE_ACCOUNT}" --resource-group "${RESOURCE_GROUP_NAME}" --location "${LOCATION}" --subscription "${AZURE_SUBSCRIPTION}"  --auth-mode login
+  fi
+
+  # Create container to store teraform information if it doesn't exist.
+  # Uses jq to parse the json output and grab the "exists" field.
+  container_exists=$(2>/dev/null az storage container exists -n "${TERAFORM_CONTAINER}" --account-name "${STORAGE_ACCOUNT}" --subscription "${AZURE_SUBSCRIPTION}" --auth-mode login | jq .exists)
+  if [[ ${container_exists} == "false" ]]; then
+      echo "Creating container ${TERAFORM_CONTAINER}"
+      1>/dev/null az storage container create -n "${TERAFORM_CONTAINER}" --account-name "${STORAGE_ACCOUNT}" --subscription "${AZURE_SUBSCRIPTION}" --auth-mode login
+  else
+      echo "Container ${TERAFORM_CONTAINER} exists."
+  fi
+
+  # Get an access key to the storage account.
+  # Use jq to grabe the "value" field of the first key. "-r" option gives raw output without quotes.
+  local sa_access_key=$(az storage account keys list --resource-group "${RESOURCE_GROUP_NAME}" --account-name "${STORAGE_ACCOUNT}" --subscription "${AZURE_SUBSCRIPTION}" | jq -r .[0].value)
+
+  #### Create AKS cluster with Terraform ####
+
+  # Initialize Terraform with a blob container to store state.
+  terraform init -backend-config="storage_account_name=${STORAGE_ACCOUNT}" -backend-config="container_name=${TERAFORM_CONTAINER}" -backend-config="access_key=${sa_access_key}" -backend-config="key=codelab.microsoft.tfstate"
+  
+  # Import the existing resource group into the configuration because we don't have perms to have Terraform be the creator of the resource group.
+  terraform import  -var resource_group_name="${RESOURCE_GROUP_NAME}" -var location="${LOCATION}" -var log_analytics_workspace_location="${LOCATION}" "azurerm_resource_group.k8s" "/subscriptions/${AZURE_SUBSCRIPTION}/resourceGroups/${RESOURCE_GROUP_NAME}"
+
+  # Have Terraform create a plan and save it to file.
+  terraform plan  -out out.plan -var resource_group_name="${RESOURCE_GROUP_NAME}" -var location="${LOCATION}" -var log_analytics_workspace_location="${LOCATION}"
+
+  # Apply the Terraform configuation.
+  # This will fail until we fix
+  # - The subscription is not registered to use namespace 'Microsoft.OperationsManagement'. See https://aka.ms/rps-not-found for how to register subscriptions.","target":"Microsoft.OperationsManagement"}
+  # - either an `identity` or `service_principal` block must be specified for cluster authentication
+  #terraform apply out.plan
 }
 
 # Run main.
